{% set version = "2.9.0.20251108" %}

package:
  name: types-python-dateutil
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-python-dateutil/types_python_dateutil-{{ version }}.tar.gz
  sha256: d8a6687e197f2fa71779ce36176c666841f811368710ab8d274b876424ebfcaa

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/dateutil-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for python-dateutil
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
