schema_version: 1

context:
  version: "2.9.0.20260508"

package:
  name: types-python-dateutil
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-python-dateutil/types_python_dateutil-${{ version }}.tar.gz
  sha256: 596a6d63d81f587bf04c8254fb78df9d2344e915ce67948d7400512e3a6206d5

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

  - package_contents:
      site_packages:
        - dateutil-stubs/__init__.pyi

about:
  summary: Typing stubs for python-dateutil
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
