schema_version: 1

context:
  version: 2.9.0.20260124

package:
  name: types-python-dateutil
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-python-dateutil/types_python_dateutil-${{ version }}.tar.gz
  sha256: 7d2db9f860820c30e5b8152bfe78dbdf795f7d1c6176057424e8b3fdd1f581af

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

  - package_contents:
      site_packages:
        - dateutil-stubs/__init__.pyi

about:
  summary: Typing stubs for python-dateutil
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
